In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
neiss_aip = pd.read_csv("neiss-aip2023.tsv", sep="\t", dtype={0: str, 'icause_c': str, 'intent_c': str, 'pcause_c': str})
neiss_aip.rename(columns={"nek": "ID"}, inplace=True)
neiss_aip.head()

,ID,traffic_c,psu,weight,bdpt_c,bdpt2_c,diag_c,diag2_c,disp_c,fire,...,sp_snowm,sp_soccr,sp_softb,sp_sski,sp_swim,sp_tobog,sp_track,sp_tramp,sp_volly,sp_wski
0,230106094,,45,76.821551,82,,59,,1,0,...,0,0,0,0,0,0,0,0,0,0
1,230106095,,45,76.821551,33,,59,,1,0,...,0,0,0,0,0,0,0,0,0,0
2,230106234,,29,76.821551,75,,59,,1,0,...,0,0,0,0,0,0,0,0,0,0
3,230106235,0,29,76.821551,82,,53,,1,0,...,0,0,0,0,0,0,0,0,0,0
4,230106236,1,29,76.821551,75,76,53,53,1,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
neiss = pd.read_csv("neiss2023.tsv", sep="\t", dtype={0: str})
neiss.rename(columns={"CPSC_Case_Number": "ID"}, inplace=True)
neiss.head()

,ID,Treatment_Date,Age,Sex,Race,Other_Race,Hispanic,Body_Part,Diagnosis,Other_Diagnosis,...,Fire_Involvement,Product_1,Product_2,Product_3,Alcohol,Drug,Narrative_1,Stratum,PSU,Weight
0,230106094,01/01/2023,34,2.0,1.0,NaN,2.0,82.0,59.0,NaN,...,0.0,478.0,0.0,0.0,0.0,0.0,34YOF WAS WASHING A GLASS THAT BROKE. DX: LA...,S,45.0,76.8216
1,230106235,01/01/2023,11,2.0,1.0,NaN,2.0,82.0,53.0,NaN,...,0.0,3286.0,0.0,0.0,0.0,0.0,11YOF INVOLVED IN FOUR WHEELER TURNOVER.DX: ...,S,29.0,76.8216
2,230106237,01/01/2023,12,2.0,1.0,NaN,2.0,30.0,53.0,NaN,...,0.0,3286.0,0.0,0.0,0.0,0.0,"12YOF WITH MVA, WAS PASSENGER ON A FOUR WHEELE...",S,29.0,76.8216
3,230106559,01/01/2023,75,2.0,1.0,NaN,2.0,76.0,59.0,NaN,...,0.0,4008.0,4076.0,4074.0,0.0,0.0,"75yof, at *** visiting husband, tripped over b...",V,22.0,15.7688
4,230106561,01/01/2023,38,2.0,1.0,NaN,2.0,75.0,62.0,NaN,...,0.0,698.0,0.0,0.0,0.0,0.0,"38YOF, FELL X 4 DAYS GETTING OUT OF HOT TUB, S...",V,22.0,15.7688

In [6]:
merged_df = pd.merge(neiss, neiss_aip, on='ID', how='inner')

In [34]:
merged_df.shape

(285486, 90)

In [35]:
print(merged_df['icause_c'].describe())
print(merged_df['intent_c'].describe())
print(merged_df['pcause_c'].describe())

count     285486
unique        17
top
freq      253037
Name: icause_c, dtype: object
count     285486
unique         3
top            0
freq      285094
Name: intent_c, dtype: object
count     285486
unique        22
top            6
freq      133696
Name: pcause_c, dtype: object

In [46]:
merged_df.groupby('icause_c').size()

icause_c
       253037
10        359
11          2
12          6
13         19
14          7
15         25
16         15
17         17
20         10
5           6
6        2656
7       26413
8        2847
88         19
9          46
999         2
dtype: int64

In [47]:
merged_df.groupby('pcause_c').size()

pcause_c
1         741
10       5903
11       2328
12        286
13        291
14        789
15       7990
16        580
17        859
18        107
19        128
2        3066
20        387
3        8934
4         515
5        6002
6      133696
7       54705
8       25616
88       4764
9       24844
999      2955
dtype: int64

In [48]:
merged_df.groupby('intent_c').size()

intent_c
0    285094
2       266
3       126
dtype: int64

In [50]:
merged_df['Narrative_1'].describe()

count                                                285486
unique                                               284734
top       15 YOM TWISTED ANKLE PLAYING BASKETBALL.  DX A...
freq                                                     17
Name: Narrative_1, dtype: object

In [7]:
merged_df.to_csv('merged_eda.csv')

In [10]:
merged_df['Narrative_1'].str.len().describe()

count    285486.000000
mean        118.279509
std          59.086089
min          24.000000
25%          76.000000
50%         104.000000
75%         144.000000
max         400.000000
Name: Narrative_1, dtype: float64

In [12]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 285486 entries, 0 to 285485
Data columns (total 90 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 285486 non-null  str
 1   Treatment_Date     285486 non-null  str
 2   Age                285486 non-null  int64
 3   Sex                285486 non-null  float64
 4   Race               285486 non-null  float64
 5   Other_Race         12701 non-null   str
 6   Hispanic           285486 non-null  float64
 7   Body_Part          285486 non-null  float64
 8   Diagnosis          285486 non-null  float64
 9   Other_Diagnosis    19452 non-null   str
 10  Body_Part_2        73285 non-null   float64
 11  Diagnosis_2        73285 non-null   float64
 12  Other_Diagnosis_2  12875 non-null   str
 13  Disposition        285486 non-null  float64
 14  Location           285486 non-null  float64
 15  Fire_Involvement   285486 non-null  float64
 16  Product_1          285486 non-null  float64
 17  Product_2          285486 non-null  float64
 18  Product_3          285486 non-null  float64
 19  Alcohol            285486 non-null  float64
 20  Drug               285486 non-null  float64
 21  Narrative_1        285486 non-null  str
 22  Stratum            285484 non-null  str
 23  PSU                285484 non-null  float64
 24  Weight             285484 non-null  float64
 25  traffic_c          285486 non-null  str
 26  psu                285486 non-null  int64
 27  weight             285486 non-null  float64
 28  bdpt_c             285486 non-null  int64
 29  bdpt2_c            285486 non-null  str
 30  diag_c             285486 non-null  int64
 31  diag2_c            285486 non-null  str
 32  disp_c             285486 non-null  int64
 33  fire               285486 non-null  int64
 34  onthejob_c         285486 non-null  int64
 35  occupant_c         285486 non-null  str
 36  perp_c             285486 non-null  str
 37  reasonassault_c    285486 non-null  str
 38  sex_c              285486 non-null  int64
 39  stratum_c          285486 non-null  int64
 40  trdate_c           285486 non-null  int64
 41  year_c             285486 non-null  int64
 42  loc_c              285486 non-null  int64
 43  hisp_c             285486 non-null  int64
 44  agemth_c           285486 non-null  int64
 45  ageyr_c            285486 non-null  int64
 46  agegroup_c         285486 non-null  int64
 47  race_c             285486 non-null  int64
 48  intent_c           285486 non-null  str
 49  pcause_c           285486 non-null  str
 50  icause_c           285486 non-null  str
 51  sp_amuse           285486 non-null  int64
 52  sp_atv             285486 non-null  int64
 53  sp_baseb           285486 non-null  int64
 54  sp_baskb           285486 non-null  int64
 55  sp_bicyc           285486 non-null  int64
 56  sp_billi           285486 non-null  int64
 57  sp_bowl            285486 non-null  int64
 58  sp_campg           285486 non-null  int64
 59  sp_cmbat           285486 non-null  int64
 60  sp_exerc           285486 non-null  int64
 61  sp_fishg           285486 non-null  int64
 62  sp_footb           285486 non-null  int64
 63  sp_gcart           285486 non-null  int64
 64  sp_golf            285486 non-null  int64
 65  sp_gymna           285486 non-null  int64
 66  sp_hocky           285486 non-null  int64
 67  sp_horse           285486 non-null  int64
 68  sp_mball           285486 non-null  int64
 69  sp_moped           285486 non-null  int64
 70  sp_npgun           285486 non-null  int64
 71  sp_other           285486 non-null  int64
 72  sp_playg           285486 non-null  int64
 73  sp_pwatr           285486 non-null  int64
 74  sp_racq            285486 non-null  int64
 75  sp_scoot           285486 non-null  int64
 76  sp_skatb           285486 non-null  int64
 77  sp_skati           285486 non-null  int64
 78  sp_skatl           285486 non-null  int64
 79  sp_skato           285486 non-null  int64
 80  sp_snowm           285486 non-null  int64
 81  sp_soccr           285486 non-null  int64
 82  sp_softb           285486 non-null  int64
 83  sp_sski            285486 non-null  int64
 84  sp_swim            285486 non-null  int64
 85  sp_tobog           285486 non-null  int64
 86  sp_track           285486 non-null  int64
 87  sp_tramp           285486 non-null  int64
 88  sp_volly           285486 non-null  int64
 89  sp_wski            285486 non-null  int64
dtypes: float64(18), int64(56), str(16)
memory usage: 196.0 MB